version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: souhailakharbech/se3-g8-springkaddem:4.0
    restart: always
    build: .
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/Kaddem/DevopsProject/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: khaddemApp
      MYSQL_ROOT_PASSWORD: root
